### ISSUE TITLE
프로젝트 컨벤션 작성

### ISSUE THREAD

**Issue by seonghoo1217** [DY-WhatSong/BE-What_Song#1]
## Issue Check
- @itsChrisJang  프로젝트 컨벤션 `README.md`에 작성하였으니 확인 부탁드립니다. - (05.03)

**Comment by seonghoo1217** [comment]
@itsChrisJang Git Flow 방식을 기존의 `Git WorkFlow` 방식에서 `trunk-based-development flow`로 변경하고자 합니다. 혹시 이에 대해서 어떻게 생각하시나요?

**Comment by itsChrisJang** [comment]
이야기를 들어보니 `trunk-based-development flow`로 진행하는 것이 괜찮겠네요 ㅎㅎ

추가적으로 
개발 도중 프론트와 테스트를 해야하는 경우가 많다고 말씀해주셨는데
Spring REST Doc 은 
거의 백엔드 API 명세서 같이 
Server To Server 연동시에 참고하는 문서 형식 느낌이 강한데
좀 더 원활하게 프론트 분들과 협업을 위해서
Swagger 만을 사용하는것이 좋겠다라는 생각이 드네요.

**Comment by seonghoo1217** [comment]
넵 동의하는 부분입니다!

이후 자세한 논의는 다시 이슈를 통해 진행하는 걸로 하겠습니다
