### ISSUE TITLE
yml 파일 환경에 따른 분리

### ISSUE THREAD

**Issue by seonghoo1217** [DY-WhatSong/BE-What_Song#21]
## AS-IS
- 테스트, 배포, 개발 환경에 관계없이 하나의 yaml 파일에서 `Config` 파일 등을 관리함
- 예를 들어 oauth, redis, jwt등 main yaml 파일에 집중되어있음

## TO-BE
- 기능(Config Domian)에 따른 분리 및 환경에 따른 분리 진행

**Comment by seonghoo1217** [comment]
@itsChrisJang 
개발환경과 기능에 따라 yml파일을 분리하여, 적용하려했지만 분리되어 실행되지 못하고 Spring Container가 이를 인지하지 못하는 이슈가 발생하였습니다

**Comment by itsChrisJang** [comment]
진행중입니다.

**Comment by seonghoo1217** [comment]
@itsChrisJang 개발환경에 따른 `Yaml` 파일 분리를 진행하였고, `개발(devleop)` 환경과 `배포(prod)` 환경에 따라 Oauth redirect-uri가 달라지는 부분이 존재하니 확인 부탁드리겠습니다.

별다른 이슈가 존재하지 않으므로 해당 Issue는 Close하겠습니다
