### ISSUE TITLE
Stomp CORS 이슈 : CustomFilter로 인하는 Stomp Cors발생

### ISSUE THREAD

**Issue by seonghoo1217** [DY-WhatSong/BE-What_Song#36]
## Issue
- 현재 WS(WebSocket) 관련 Config class인 `StompConfig`에  Cors 설정을 별도로 해주었지만, Client와의 Connect시에 발생하는 Cors 이슈
  - 트러블 슈팅을 위해 Security관련 Filter 및 설정 값을 초기화
  - 그 결과, Custom Filter 중 하나인 JWT 토큰 관련 필터 설정이 Stomp Connection을 막는다는 것을 알게됨

## Trouble Shooting
- Filter에 Stomp 관련 Connection 요청시의 별도 동작로직 구현

**Comment by itsChrisJang** [comment]
감사합니다.
